[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "index.html"
  SECRETS_SCAN_OMIT_KEYS = "TURNSTILE_SECRET"

[[redirects]]
  from = "/api/verify"
  to = "/.netlify/functions/verify"
  status = 200

[[redirects]]
  from = "/s/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/entry"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://www.google.com"
  status = 302
